-- ═══════════════════════════════════════════════════════════════
-- SafeCode Asset Transfer Tracking Schema
-- ═══════════════════════════════════════════════════════════════

-- Asset source types
-- 'self' = generated by user
-- 'user_transfer' = received from another user
-- 'admin_transfer' = received from admin

-- ═══ Extend codes table ═══
ALTER TABLE codes ADD COLUMN IF NOT EXISTS source_type VARCHAR(50) DEFAULT 'self' 
  CHECK(source_type IN ('self', 'user_transfer', 'admin_transfer'));

ALTER TABLE codes ADD COLUMN IF NOT EXISTS source_email VARCHAR(255);
ALTER TABLE codes ADD COLUMN IF NOT EXISTS transferred_at TIMESTAMP;
ALTER TABLE codes ADD COLUMN IF NOT EXISTS transferred_from_email VARCHAR(255);

-- ═══ Extend silver_assets table ═══
ALTER TABLE silver_assets ADD COLUMN IF NOT EXISTS source_type VARCHAR(50) DEFAULT 'self' 
  CHECK(source_type IN ('self', 'user_transfer', 'admin_transfer'));

ALTER TABLE silver_assets ADD COLUMN IF NOT EXISTS source_email VARCHAR(255);
ALTER TABLE silver_assets ADD COLUMN IF NOT EXISTS transferred_at TIMESTAMP;
ALTER TABLE silver_assets ADD COLUMN IF NOT EXISTS transferred_from_email VARCHAR(255);

-- ═══ Extend gold_assets table ═══
ALTER TABLE gold_assets ADD COLUMN IF NOT EXISTS source_type VARCHAR(50) DEFAULT 'self' 
  CHECK(source_type IN ('self', 'user_transfer', 'admin_transfer'));

ALTER TABLE gold_assets ADD COLUMN IF NOT EXISTS source_email VARCHAR(255);
ALTER TABLE gold_assets ADD COLUMN IF NOT EXISTS transferred_at TIMESTAMP;
ALTER TABLE gold_assets ADD COLUMN IF NOT EXISTS transferred_from_email VARCHAR(255);

-- ═══ Create transfer history table ═══
CREATE TABLE IF NOT EXISTS asset_transfers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id VARCHAR(255) NOT NULL,
  asset_type VARCHAR(50) NOT NULL CHECK(asset_type IN ('code', 'silver', 'gold')),
  
  -- Transfer details
  from_email VARCHAR(255) NOT NULL,
  to_email VARCHAR(255) NOT NULL,
  transfer_type VARCHAR(50) NOT NULL CHECK(transfer_type IN ('user', 'admin')),
  
  -- Metadata
  transferred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  message TEXT,
  status VARCHAR(50) DEFAULT 'completed' CHECK(status IN ('pending', 'completed', 'rejected')),
  
  -- Audit
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_ip VARCHAR(45)
);

-- ═══ Create indices for fast queries ═══
CREATE INDEX IF NOT EXISTS idx_transfers_to_email ON asset_transfers(to_email, transferred_at DESC);
CREATE INDEX IF NOT EXISTS idx_transfers_from_email ON asset_transfers(from_email, transferred_at DESC);
CREATE INDEX IF NOT EXISTS idx_transfers_asset ON asset_transfers(asset_id, asset_type);
CREATE INDEX IF NOT EXISTS idx_codes_source ON codes(source_type, source_email);
CREATE INDEX IF NOT EXISTS idx_silver_source ON silver_assets(source_type, source_email);
CREATE INDEX IF NOT EXISTS idx_gold_source ON gold_assets(source_type, source_email);

-- ═══ Sample data (for testing) ═══
-- Self-generated assets (default, no changes)
-- User-transferred assets
-- UPDATE codes SET source_type='user_transfer', transferred_from_email='alice@example.com', transferred_at=NOW() 
--   WHERE id = 'some-code-id';
-- Admin-transferred assets
-- UPDATE codes SET source_type='admin_transfer', transferred_from_email='admin@company.com', transferred_at=NOW() 
--   WHERE id = 'another-code-id';
