"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CollapsibleContent = exports.CollapsibleTrigger = exports.Collapsible = void 0;
const CollapsiblePrimitive = require("@radix-ui/react-collapsible");
const Collapsible = CollapsiblePrimitive.Root;
exports.Collapsible = Collapsible;
const CollapsibleTrigger = CollapsiblePrimitive.CollapsibleTrigger;
exports.CollapsibleTrigger = CollapsibleTrigger;
const CollapsibleContent = CollapsiblePrimitive.CollapsibleContent;
exports.CollapsibleContent = CollapsibleContent;
